export const labels = {
    sendAdvice: "Wyślij poradę",
    parentPhoneNumber: "Numer telefonu rodzica",
    patientName: "Imię pacjenta",
    professionalName: "Imię, nazwisko i funkcja medyka",
    requiredField: "To pole jest wymagane",
    phoneNumberMustBeValid: "Numer telefonu musi być prawidłowy",
    advice: "Porada",
    resetForm: "Resetuj formularz",
    sendingAdvice: "Wysyłanie porady...",
    showAdvice: "Pokaż poradę",
    options: "Opcja",
    searchAdvice: "Szukaj",
    showAll: "Wszystkie",
    close: "Zamknij",
    logOut: "Wyloguj się",
    logIn: "Zaloguj się",
    loading: "Ładowanie",
    yourAccountIsNotConfirmed: "Twoje konto nie jest potwierdzone",
    adviceList: "Lista porad",
    aboutApp: "O aplikacji",
    yourAccountIsNotConfirmedAdMedicalprofessionalExplanation:
        "Twoje konto nie jest oznaczone jako konto medyka. " +
        "Skontaktuj się z administratorem w celu potwierdzenia Twojego konta.",
    adviceCode: "Kod porady",
};
